# Generated by Django 2.0.1 on 2022-04-16 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Emotions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emotions', models.CharField(max_length=255)),
                ('text', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('emotions', models.ManyToManyField(to='app.Emotions')),
            ],
        ),
        migrations.CreateModel(
            name='Figures',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('name2', models.CharField(max_length=255)),
                ('birth', models.CharField(max_length=255)),
                ('death', models.CharField(max_length=255)),
                ('descriptions', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('relations', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Locations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locations', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='events',
            name='figures',
            field=models.ManyToManyField(to='app.Figures'),
        ),
        migrations.AddField(
            model_name='events',
            name='locations',
            field=models.ManyToManyField(to='app.Locations'),
        ),
        migrations.AddField(
            model_name='emotions',
            name='figures',
            field=models.ManyToManyField(to='app.Figures'),
        ),
    ]
